/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.miu.cs.cs489.lab1b;

import com.fasterxml.jackson.core.JsonProcessingException;
import edu.miu.cs.cs489.lab1b.model.Employee;
import edu.miu.cs.cs489.lab1b.model.PensionPlan;
import edu.miu.cs.cs489.lab1b.service.EmployeeService;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class App {

    public static void main(String[] args) throws JsonProcessingException {
        List<Employee> employees = new ArrayList<>();
        employees.add(new Employee(1, "Daniel", "Agar", LocalDate.of(20118, 1, 17), 105945.50, new PensionPlan("EX1089", LocalDate.of(2023, 1, 17), 100.00)));
        employees.add(new Employee(2, "Bernard", "Shaw", LocalDate.of(2019, 4, 3), 197750.00, null));
        employees.add(new Employee(3, "Carly", "Agar", LocalDate.of(2014, 5, 16), 842000.75, new PensionPlan("SM2307", LocalDate.of(2019, 11, 4), 1555.50)));
        employees.add(new Employee(4, "Wesley", "Schneider", LocalDate.of(2019, 9, 2), 74500.00, null));

        EmployeeService service = new EmployeeService(employees);

        // Get all employees in JSON
        System.out.println("All Employees:");
        System.out.println(service.getAllEmployeesInJson());

        // Get monthly upcoming enrollees report
        System.out.println("Monthly Upcoming Enrollees:");
        System.out.println(service.getMonthlyUpcomingEnrolleesReport());
    }
}
