/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.miu.cs.cs489;

import edu.miu.cs.cs489.lab1b.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {

    }
}
